// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: api/wafTop/v1/normal_http.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NormalHttp_CreateNormalHttp_FullMethodName = "/api.wafTop.v1.NormalHttp/CreateNormalHttp"
	NormalHttp_UpdateNormalHttp_FullMethodName = "/api.wafTop.v1.NormalHttp/UpdateNormalHttp"
	NormalHttp_DeleteNormalHttp_FullMethodName = "/api.wafTop.v1.NormalHttp/DeleteNormalHttp"
	NormalHttp_GetNormalHttp_FullMethodName    = "/api.wafTop.v1.NormalHttp/GetNormalHttp"
	NormalHttp_ListNormalHttp_FullMethodName   = "/api.wafTop.v1.NormalHttp/ListNormalHttp"
)

// NormalHttpClient is the client API for NormalHttp service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NormalHttpClient interface {
	CreateNormalHttp(ctx context.Context, in *CreateNormalHttpRequest, opts ...grpc.CallOption) (*CreateNormalHttpReply, error)
	UpdateNormalHttp(ctx context.Context, in *UpdateNormalHttpRequest, opts ...grpc.CallOption) (*UpdateNormalHttpReply, error)
	DeleteNormalHttp(ctx context.Context, in *DeleteNormalHttpRequest, opts ...grpc.CallOption) (*DeleteNormalHttpReply, error)
	GetNormalHttp(ctx context.Context, in *GetNormalHttpRequest, opts ...grpc.CallOption) (*GetNormalHttpReply, error)
	ListNormalHttp(ctx context.Context, in *ListNormalHttpRequest, opts ...grpc.CallOption) (*ListNormalHttpReply, error)
}

type normalHttpClient struct {
	cc grpc.ClientConnInterface
}

func NewNormalHttpClient(cc grpc.ClientConnInterface) NormalHttpClient {
	return &normalHttpClient{cc}
}

func (c *normalHttpClient) CreateNormalHttp(ctx context.Context, in *CreateNormalHttpRequest, opts ...grpc.CallOption) (*CreateNormalHttpReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateNormalHttpReply)
	err := c.cc.Invoke(ctx, NormalHttp_CreateNormalHttp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *normalHttpClient) UpdateNormalHttp(ctx context.Context, in *UpdateNormalHttpRequest, opts ...grpc.CallOption) (*UpdateNormalHttpReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateNormalHttpReply)
	err := c.cc.Invoke(ctx, NormalHttp_UpdateNormalHttp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *normalHttpClient) DeleteNormalHttp(ctx context.Context, in *DeleteNormalHttpRequest, opts ...grpc.CallOption) (*DeleteNormalHttpReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteNormalHttpReply)
	err := c.cc.Invoke(ctx, NormalHttp_DeleteNormalHttp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *normalHttpClient) GetNormalHttp(ctx context.Context, in *GetNormalHttpRequest, opts ...grpc.CallOption) (*GetNormalHttpReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNormalHttpReply)
	err := c.cc.Invoke(ctx, NormalHttp_GetNormalHttp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *normalHttpClient) ListNormalHttp(ctx context.Context, in *ListNormalHttpRequest, opts ...grpc.CallOption) (*ListNormalHttpReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListNormalHttpReply)
	err := c.cc.Invoke(ctx, NormalHttp_ListNormalHttp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NormalHttpServer is the server API for NormalHttp service.
// All implementations must embed UnimplementedNormalHttpServer
// for forward compatibility.
type NormalHttpServer interface {
	CreateNormalHttp(context.Context, *CreateNormalHttpRequest) (*CreateNormalHttpReply, error)
	UpdateNormalHttp(context.Context, *UpdateNormalHttpRequest) (*UpdateNormalHttpReply, error)
	DeleteNormalHttp(context.Context, *DeleteNormalHttpRequest) (*DeleteNormalHttpReply, error)
	GetNormalHttp(context.Context, *GetNormalHttpRequest) (*GetNormalHttpReply, error)
	ListNormalHttp(context.Context, *ListNormalHttpRequest) (*ListNormalHttpReply, error)
	mustEmbedUnimplementedNormalHttpServer()
}

// UnimplementedNormalHttpServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNormalHttpServer struct{}

func (UnimplementedNormalHttpServer) CreateNormalHttp(context.Context, *CreateNormalHttpRequest) (*CreateNormalHttpReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateNormalHttp not implemented")
}
func (UnimplementedNormalHttpServer) UpdateNormalHttp(context.Context, *UpdateNormalHttpRequest) (*UpdateNormalHttpReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateNormalHttp not implemented")
}
func (UnimplementedNormalHttpServer) DeleteNormalHttp(context.Context, *DeleteNormalHttpRequest) (*DeleteNormalHttpReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteNormalHttp not implemented")
}
func (UnimplementedNormalHttpServer) GetNormalHttp(context.Context, *GetNormalHttpRequest) (*GetNormalHttpReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNormalHttp not implemented")
}
func (UnimplementedNormalHttpServer) ListNormalHttp(context.Context, *ListNormalHttpRequest) (*ListNormalHttpReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListNormalHttp not implemented")
}
func (UnimplementedNormalHttpServer) mustEmbedUnimplementedNormalHttpServer() {}
func (UnimplementedNormalHttpServer) testEmbeddedByValue()                    {}

// UnsafeNormalHttpServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NormalHttpServer will
// result in compilation errors.
type UnsafeNormalHttpServer interface {
	mustEmbedUnimplementedNormalHttpServer()
}

func RegisterNormalHttpServer(s grpc.ServiceRegistrar, srv NormalHttpServer) {
	// If the following call pancis, it indicates UnimplementedNormalHttpServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NormalHttp_ServiceDesc, srv)
}

func _NormalHttp_CreateNormalHttp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNormalHttpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NormalHttpServer).CreateNormalHttp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NormalHttp_CreateNormalHttp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NormalHttpServer).CreateNormalHttp(ctx, req.(*CreateNormalHttpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NormalHttp_UpdateNormalHttp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateNormalHttpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NormalHttpServer).UpdateNormalHttp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NormalHttp_UpdateNormalHttp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NormalHttpServer).UpdateNormalHttp(ctx, req.(*UpdateNormalHttpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NormalHttp_DeleteNormalHttp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteNormalHttpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NormalHttpServer).DeleteNormalHttp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NormalHttp_DeleteNormalHttp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NormalHttpServer).DeleteNormalHttp(ctx, req.(*DeleteNormalHttpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NormalHttp_GetNormalHttp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNormalHttpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NormalHttpServer).GetNormalHttp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NormalHttp_GetNormalHttp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NormalHttpServer).GetNormalHttp(ctx, req.(*GetNormalHttpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NormalHttp_ListNormalHttp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNormalHttpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NormalHttpServer).ListNormalHttp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NormalHttp_ListNormalHttp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NormalHttpServer).ListNormalHttp(ctx, req.(*ListNormalHttpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NormalHttp_ServiceDesc is the grpc.ServiceDesc for NormalHttp service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NormalHttp_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.wafTop.v1.NormalHttp",
	HandlerType: (*NormalHttpServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateNormalHttp",
			Handler:    _NormalHttp_CreateNormalHttp_Handler,
		},
		{
			MethodName: "UpdateNormalHttp",
			Handler:    _NormalHttp_UpdateNormalHttp_Handler,
		},
		{
			MethodName: "DeleteNormalHttp",
			Handler:    _NormalHttp_DeleteNormalHttp_Handler,
		},
		{
			MethodName: "GetNormalHttp",
			Handler:    _NormalHttp_GetNormalHttp_Handler,
		},
		{
			MethodName: "ListNormalHttp",
			Handler:    _NormalHttp_ListNormalHttp_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/wafTop/v1/normal_http.proto",
}
