// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.8.3
// - protoc             v3.12.4
// source: v1/server_principal.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationServerPrincipalGetServerPrincipal = "/api.wafTop.v1.ServerPrincipal/GetServerPrincipal"

type ServerPrincipalHTTPServer interface {
	GetServerPrincipal(context.Context, *GetServerPrincipalRequest) (*GetServerPrincipalReply, error)
}

func RegisterServerPrincipalHTTPServer(s *http.Server, srv ServerPrincipalHTTPServer) {
	r := s.Route("/")
	r.POST("/app/waf_top/v1/server_principal", _ServerPrincipal_GetServerPrincipal0_HTTP_Handler(srv))
}

func _ServerPrincipal_GetServerPrincipal0_HTTP_Handler(srv ServerPrincipalHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetServerPrincipalRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationServerPrincipalGetServerPrincipal)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetServerPrincipal(ctx, req.(*GetServerPrincipalRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetServerPrincipalReply)
		return ctx.Result(200, reply)
	}
}

type ServerPrincipalHTTPClient interface {
	GetServerPrincipal(ctx context.Context, req *GetServerPrincipalRequest, opts ...http.CallOption) (rsp *GetServerPrincipalReply, err error)
}

type ServerPrincipalHTTPClientImpl struct {
	cc *http.Client
}

func NewServerPrincipalHTTPClient(client *http.Client) ServerPrincipalHTTPClient {
	return &ServerPrincipalHTTPClientImpl{client}
}

func (c *ServerPrincipalHTTPClientImpl) GetServerPrincipal(ctx context.Context, in *GetServerPrincipalRequest, opts ...http.CallOption) (*GetServerPrincipalReply, error) {
	var out GetServerPrincipalReply
	pattern := "/app/waf_top/v1/server_principal"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationServerPrincipalGetServerPrincipal))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
