// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: v1/server_principal.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ServerPrincipal_GetServerPrincipal_FullMethodName = "/api.wafTop.v1.ServerPrincipal/GetServerPrincipal"
)

// ServerPrincipalClient is the client API for ServerPrincipal service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServerPrincipalClient interface {
	GetServerPrincipal(ctx context.Context, in *GetServerPrincipalRequest, opts ...grpc.CallOption) (*GetServerPrincipalReply, error)
}

type serverPrincipalClient struct {
	cc grpc.ClientConnInterface
}

func NewServerPrincipalClient(cc grpc.ClientConnInterface) ServerPrincipalClient {
	return &serverPrincipalClient{cc}
}

func (c *serverPrincipalClient) GetServerPrincipal(ctx context.Context, in *GetServerPrincipalRequest, opts ...grpc.CallOption) (*GetServerPrincipalReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetServerPrincipalReply)
	err := c.cc.Invoke(ctx, ServerPrincipal_GetServerPrincipal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServerPrincipalServer is the server API for ServerPrincipal service.
// All implementations must embed UnimplementedServerPrincipalServer
// for forward compatibility.
type ServerPrincipalServer interface {
	GetServerPrincipal(context.Context, *GetServerPrincipalRequest) (*GetServerPrincipalReply, error)
	mustEmbedUnimplementedServerPrincipalServer()
}

// UnimplementedServerPrincipalServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedServerPrincipalServer struct{}

func (UnimplementedServerPrincipalServer) GetServerPrincipal(context.Context, *GetServerPrincipalRequest) (*GetServerPrincipalReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetServerPrincipal not implemented")
}
func (UnimplementedServerPrincipalServer) mustEmbedUnimplementedServerPrincipalServer() {}
func (UnimplementedServerPrincipalServer) testEmbeddedByValue()                         {}

// UnsafeServerPrincipalServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServerPrincipalServer will
// result in compilation errors.
type UnsafeServerPrincipalServer interface {
	mustEmbedUnimplementedServerPrincipalServer()
}

func RegisterServerPrincipalServer(s grpc.ServiceRegistrar, srv ServerPrincipalServer) {
	// If the following call pancis, it indicates UnimplementedServerPrincipalServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ServerPrincipal_ServiceDesc, srv)
}

func _ServerPrincipal_GetServerPrincipal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetServerPrincipalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerPrincipalServer).GetServerPrincipal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServerPrincipal_GetServerPrincipal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerPrincipalServer).GetServerPrincipal(ctx, req.(*GetServerPrincipalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ServerPrincipal_ServiceDesc is the grpc.ServiceDesc for ServerPrincipal service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ServerPrincipal_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.wafTop.v1.ServerPrincipal",
	HandlerType: (*ServerPrincipalServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetServerPrincipal",
			Handler:    _ServerPrincipal_GetServerPrincipal_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1/server_principal.proto",
}
