// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.8.0
// - protoc             v4.25.2
// source: api/wafTop/v1/server.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationServerCreateServer = "/api.wafTop.v1.Server/CreateServer"
const OperationServerDeleteServer = "/api.wafTop.v1.Server/DeleteServer"
const OperationServerGetServer = "/api.wafTop.v1.Server/GetServer"
const OperationServerListServer = "/api.wafTop.v1.Server/ListServer"
const OperationServerUpdateServer = "/api.wafTop.v1.Server/UpdateServer"

type ServerHTTPServer interface {
	CreateServer(context.Context, *ChangeServerRequest) (*CreateServerReply, error)
	DeleteServer(context.Context, *DeleteRequest) (*DeleteReply, error)
	GetServer(context.Context, *GetServerRequest) (*GetServerReply, error)
	ListServer(context.Context, *ListServerRequest) (*ListServerReply, error)
	UpdateServer(context.Context, *ChangeServerRequest) (*UpdateServerReply, error)
}

func RegisterServerHTTPServer(s *http.Server, srv ServerHTTPServer) {
	r := s.Route("/")
	r.POST("/app/wafTop/v1/serverWaf", _Server_CreateServer0_HTTP_Handler(srv))
	r.PATCH("/app/wafTop/v1/serverWaf", _Server_UpdateServer0_HTTP_Handler(srv))
	r.DELETE("/app/wafTop/v1/serverWaf", _Server_DeleteServer0_HTTP_Handler(srv))
	r.GET("/app/wafTop/v1/serverWaf/{id}", _Server_GetServer0_HTTP_Handler(srv))
	r.GET("/app/wafTop/v1/serverWafs", _Server_ListServer0_HTTP_Handler(srv))
}

func _Server_CreateServer0_HTTP_Handler(srv ServerHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ChangeServerRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationServerCreateServer)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateServer(ctx, req.(*ChangeServerRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateServerReply)
		return ctx.Result(200, reply)
	}
}

func _Server_UpdateServer0_HTTP_Handler(srv ServerHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ChangeServerRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationServerUpdateServer)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateServer(ctx, req.(*ChangeServerRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateServerReply)
		return ctx.Result(200, reply)
	}
}

func _Server_DeleteServer0_HTTP_Handler(srv ServerHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationServerDeleteServer)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteServer(ctx, req.(*DeleteRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteReply)
		return ctx.Result(200, reply)
	}
}

func _Server_GetServer0_HTTP_Handler(srv ServerHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetServerRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationServerGetServer)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetServer(ctx, req.(*GetServerRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetServerReply)
		return ctx.Result(200, reply)
	}
}

func _Server_ListServer0_HTTP_Handler(srv ServerHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListServerRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationServerListServer)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListServer(ctx, req.(*ListServerRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListServerReply)
		return ctx.Result(200, reply)
	}
}

type ServerHTTPClient interface {
	CreateServer(ctx context.Context, req *ChangeServerRequest, opts ...http.CallOption) (rsp *CreateServerReply, err error)
	DeleteServer(ctx context.Context, req *DeleteRequest, opts ...http.CallOption) (rsp *DeleteReply, err error)
	GetServer(ctx context.Context, req *GetServerRequest, opts ...http.CallOption) (rsp *GetServerReply, err error)
	ListServer(ctx context.Context, req *ListServerRequest, opts ...http.CallOption) (rsp *ListServerReply, err error)
	UpdateServer(ctx context.Context, req *ChangeServerRequest, opts ...http.CallOption) (rsp *UpdateServerReply, err error)
}

type ServerHTTPClientImpl struct {
	cc *http.Client
}

func NewServerHTTPClient(client *http.Client) ServerHTTPClient {
	return &ServerHTTPClientImpl{client}
}

func (c *ServerHTTPClientImpl) CreateServer(ctx context.Context, in *ChangeServerRequest, opts ...http.CallOption) (*CreateServerReply, error) {
	var out CreateServerReply
	pattern := "/app/wafTop/v1/serverWaf"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationServerCreateServer))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ServerHTTPClientImpl) DeleteServer(ctx context.Context, in *DeleteRequest, opts ...http.CallOption) (*DeleteReply, error) {
	var out DeleteReply
	pattern := "/app/wafTop/v1/serverWaf"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationServerDeleteServer))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ServerHTTPClientImpl) GetServer(ctx context.Context, in *GetServerRequest, opts ...http.CallOption) (*GetServerReply, error) {
	var out GetServerReply
	pattern := "/app/wafTop/v1/serverWaf/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationServerGetServer))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ServerHTTPClientImpl) ListServer(ctx context.Context, in *ListServerRequest, opts ...http.CallOption) (*ListServerReply, error) {
	var out ListServerReply
	pattern := "/app/wafTop/v1/serverWafs"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationServerListServer))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ServerHTTPClientImpl) UpdateServer(ctx context.Context, in *ChangeServerRequest, opts ...http.CallOption) (*UpdateServerReply, error) {
	var out UpdateServerReply
	pattern := "/app/wafTop/v1/serverWaf"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationServerUpdateServer))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PATCH", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
