// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: v1/server_principal.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ServerPrincipal_GetServerPrincipalByServerId_FullMethodName = "/api.wafTop.v1.ServerPrincipal/GetServerPrincipalByServerId"
	ServerPrincipal_CreateServerPrincipal_FullMethodName        = "/api.wafTop.v1.ServerPrincipal/CreateServerPrincipal"
	ServerPrincipal_UpdateServerPrincipal_FullMethodName        = "/api.wafTop.v1.ServerPrincipal/UpdateServerPrincipal"
	ServerPrincipal_DeleteServerPrincipal_FullMethodName        = "/api.wafTop.v1.ServerPrincipal/DeleteServerPrincipal"
)

// ServerPrincipalClient is the client API for ServerPrincipal service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServerPrincipalClient interface {
	GetServerPrincipalByServerId(ctx context.Context, in *GetServerPrincipalRequest, opts ...grpc.CallOption) (*GetServerPrincipalReply, error)
	CreateServerPrincipal(ctx context.Context, in *CreateServerPrincipalRequest, opts ...grpc.CallOption) (*CreateServerPrincipalReply, error)
	UpdateServerPrincipal(ctx context.Context, in *UpdateServerPrincipalRequest, opts ...grpc.CallOption) (*UpdateServerPrincipalReply, error)
	DeleteServerPrincipal(ctx context.Context, in *DeleteServerPrincipalRequest, opts ...grpc.CallOption) (*DeleteServerPrincipalReply, error)
}

type serverPrincipalClient struct {
	cc grpc.ClientConnInterface
}

func NewServerPrincipalClient(cc grpc.ClientConnInterface) ServerPrincipalClient {
	return &serverPrincipalClient{cc}
}

func (c *serverPrincipalClient) GetServerPrincipalByServerId(ctx context.Context, in *GetServerPrincipalRequest, opts ...grpc.CallOption) (*GetServerPrincipalReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetServerPrincipalReply)
	err := c.cc.Invoke(ctx, ServerPrincipal_GetServerPrincipalByServerId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverPrincipalClient) CreateServerPrincipal(ctx context.Context, in *CreateServerPrincipalRequest, opts ...grpc.CallOption) (*CreateServerPrincipalReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateServerPrincipalReply)
	err := c.cc.Invoke(ctx, ServerPrincipal_CreateServerPrincipal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverPrincipalClient) UpdateServerPrincipal(ctx context.Context, in *UpdateServerPrincipalRequest, opts ...grpc.CallOption) (*UpdateServerPrincipalReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateServerPrincipalReply)
	err := c.cc.Invoke(ctx, ServerPrincipal_UpdateServerPrincipal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverPrincipalClient) DeleteServerPrincipal(ctx context.Context, in *DeleteServerPrincipalRequest, opts ...grpc.CallOption) (*DeleteServerPrincipalReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteServerPrincipalReply)
	err := c.cc.Invoke(ctx, ServerPrincipal_DeleteServerPrincipal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServerPrincipalServer is the server API for ServerPrincipal service.
// All implementations must embed UnimplementedServerPrincipalServer
// for forward compatibility.
type ServerPrincipalServer interface {
	GetServerPrincipalByServerId(context.Context, *GetServerPrincipalRequest) (*GetServerPrincipalReply, error)
	CreateServerPrincipal(context.Context, *CreateServerPrincipalRequest) (*CreateServerPrincipalReply, error)
	UpdateServerPrincipal(context.Context, *UpdateServerPrincipalRequest) (*UpdateServerPrincipalReply, error)
	DeleteServerPrincipal(context.Context, *DeleteServerPrincipalRequest) (*DeleteServerPrincipalReply, error)
	mustEmbedUnimplementedServerPrincipalServer()
}

// UnimplementedServerPrincipalServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedServerPrincipalServer struct{}

func (UnimplementedServerPrincipalServer) GetServerPrincipalByServerId(context.Context, *GetServerPrincipalRequest) (*GetServerPrincipalReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetServerPrincipalByServerId not implemented")
}
func (UnimplementedServerPrincipalServer) CreateServerPrincipal(context.Context, *CreateServerPrincipalRequest) (*CreateServerPrincipalReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateServerPrincipal not implemented")
}
func (UnimplementedServerPrincipalServer) UpdateServerPrincipal(context.Context, *UpdateServerPrincipalRequest) (*UpdateServerPrincipalReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateServerPrincipal not implemented")
}
func (UnimplementedServerPrincipalServer) DeleteServerPrincipal(context.Context, *DeleteServerPrincipalRequest) (*DeleteServerPrincipalReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteServerPrincipal not implemented")
}
func (UnimplementedServerPrincipalServer) mustEmbedUnimplementedServerPrincipalServer() {}
func (UnimplementedServerPrincipalServer) testEmbeddedByValue()                         {}

// UnsafeServerPrincipalServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServerPrincipalServer will
// result in compilation errors.
type UnsafeServerPrincipalServer interface {
	mustEmbedUnimplementedServerPrincipalServer()
}

func RegisterServerPrincipalServer(s grpc.ServiceRegistrar, srv ServerPrincipalServer) {
	// If the following call pancis, it indicates UnimplementedServerPrincipalServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ServerPrincipal_ServiceDesc, srv)
}

func _ServerPrincipal_GetServerPrincipalByServerId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetServerPrincipalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerPrincipalServer).GetServerPrincipalByServerId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServerPrincipal_GetServerPrincipalByServerId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerPrincipalServer).GetServerPrincipalByServerId(ctx, req.(*GetServerPrincipalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServerPrincipal_CreateServerPrincipal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateServerPrincipalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerPrincipalServer).CreateServerPrincipal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServerPrincipal_CreateServerPrincipal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerPrincipalServer).CreateServerPrincipal(ctx, req.(*CreateServerPrincipalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServerPrincipal_UpdateServerPrincipal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateServerPrincipalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerPrincipalServer).UpdateServerPrincipal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServerPrincipal_UpdateServerPrincipal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerPrincipalServer).UpdateServerPrincipal(ctx, req.(*UpdateServerPrincipalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServerPrincipal_DeleteServerPrincipal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteServerPrincipalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerPrincipalServer).DeleteServerPrincipal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServerPrincipal_DeleteServerPrincipal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerPrincipalServer).DeleteServerPrincipal(ctx, req.(*DeleteServerPrincipalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ServerPrincipal_ServiceDesc is the grpc.ServiceDesc for ServerPrincipal service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ServerPrincipal_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.wafTop.v1.ServerPrincipal",
	HandlerType: (*ServerPrincipalServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetServerPrincipalByServerId",
			Handler:    _ServerPrincipal_GetServerPrincipalByServerId_Handler,
		},
		{
			MethodName: "CreateServerPrincipal",
			Handler:    _ServerPrincipal_CreateServerPrincipal_Handler,
		},
		{
			MethodName: "UpdateServerPrincipal",
			Handler:    _ServerPrincipal_UpdateServerPrincipal_Handler,
		},
		{
			MethodName: "DeleteServerPrincipal",
			Handler:    _ServerPrincipal_DeleteServerPrincipal_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1/server_principal.proto",
}
