server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  click_house:
    dsn: tcp://127.0.0.1:9000/waf?username=default&dial_timeout=10s&read_timeout=20s
  kafka:
    group_id: group1
    addr: 127.0.0.1:9092
    assignor: range
  redis:
    addr: 127.0.0.1:6379
    db: 0