server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  click_house:
    dsn: tcp://192.168.10.4:9000/waf?username=default&dial_timeout=10s&read_timeout=20s
  kafka:
    group_id: group1
    addr: 192.168.10.4:9092
    assignor: range
  redis:
    addr: 192.168.10.4:6379
    db: 0
    password: '123456'