version: '3'

networks:
  waf-network:
    driver: bridge

services:
  # WafCoraza服务
  wafcoraza:
    build:
      context: ./wafcoraza
      dockerfile: Dockerfile
    container_name: wafcoraza
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - PROJECT_ROOT=/
    volumes:
      - ./wafcoraza/conf:/wafcoraza/conf
      - ./wafcoraza/ruleset:/wafcoraza/ruleset
      - ./wafcoraza/waf_log:/wafcoraza/waf_log
    ports:
      - "8887:8887"
    networks:
      - waf-network

  # Analyse服务
  analyse:
    build:
      context: ./analyse
      dockerfile: Dockerfile
    container_name: analyse
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - PROJECT_ROOT=/
    volumes:
      - ./analyse/configs:/configs
    ports:
      - "8000:8000"
    networks:
      - waf-network
    depends_on:
      - wafcoraza