// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/go-kratos/kratos/v2/registry"
	"wafconsole/app/cron/internal/biz/normalhttp"
	"wafconsole/app/cron/internal/conf"
	"wafconsole/app/cron/internal/data"
	"wafconsole/app/cron/internal/data/discovery"
	"wafconsole/app/cron/internal/server"
	"wafconsole/app/cron/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, confRegistry *conf.Registry, logger log.Logger, registrar registry.Registrar) (*kratos.App, func(), error) {
	registryDiscovery := discovery.NewDiscovery(confRegistry)
	normalHttpClient := discovery.NewNormalHttpRpc(registryDiscovery)
	dataData, cleanup, err := data.NewData(confData, logger, normalHttpClient)
	if err != nil {
		return nil, nil, err
	}
	repoNormalHttp := data.NewNormalHttpRepo(dataData, logger)
	usercaseNormalHttp := normalhttp.NewUsercaseNormalHttp(repoNormalHttp, logger)
	normalHttpService := service.NewServiceNormalHttp(logger, usercaseNormalHttp)
	cronService := service.NewJobService(normalHttpService)
	cronServer := server.NewCronServer(cronService, logger)
	app := newApp(logger, cronServer)
	return app, func() {
		cleanup()
	}, nil
}
