// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"wafconsole/app/dashBorad/internal/biz/viewLogic"
	"wafconsole/app/dashBorad/internal/conf"
	"wafconsole/app/dashBorad/internal/data"
	"wafconsole/app/dashBorad/internal/server"
	"wafconsole/app/dashBorad/internal/service/view"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
//
//go:generate wire
func wireApp(confServer *conf.Server, bootstrap *conf.Bootstrap, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confServer, bootstrap)
	if err != nil {
		return nil, nil, err
	}
	dataViewRepo := data.NewDataViewRepo(dataData)
	dataViewUsecase := viewLogic.NewDataViewUsecase(dataViewRepo)
	dataViewService := view.NewDataViewService(dataViewUsecase)
	grpcServer := server.NewGRPCServer(confServer, dataViewService, logger)
	httpServer := server.NewHTTPServer(confServer, dataViewService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
