server:
  http:
    addr: 0.0.0.0:8001
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9001
    timeout: 1s
data:
  mysql:
    host: 192.168.10.4
    port: 3310
    user: root
    password: '123456'
    db: DingHaiWAF
    max_idle: 10
    max_open: 100
  redis:
    addr: 192.168.10.4:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
  etcd:
    host: 192.168.10.4:2379

