server:
  http:
    addr: 0.0.0.0:8001
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  mysql:
    host: 127.0.0.1
    port: 3306
    user: root
    password: 123456
    db: DingHaiWAF
    max_idle: 10
    max_open: 100
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
