// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v4.25.2
// source: api/dashBorad/v1/message.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// #### 获取今日攻击信息 攻击数 异常IP数 , 较昨日增长数据
type GetAttackInfoFromDayRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetAttackInfoFromDayRequest) Reset() {
	*x = GetAttackInfoFromDayRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_dashBorad_v1_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAttackInfoFromDayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAttackInfoFromDayRequest) ProtoMessage() {}

func (x *GetAttackInfoFromDayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_dashBorad_v1_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAttackInfoFromDayRequest.ProtoReflect.Descriptor instead.
func (*GetAttackInfoFromDayRequest) Descriptor() ([]byte, []int) {
	return file_api_dashBorad_v1_message_proto_rawDescGZIP(), []int{0}
}

type GetAttackInfoFromDayReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AttackCount   int64   `protobuf:"varint,1,opt,name=attack_count,json=attackCount,proto3" json:"attack_count,omitempty"`
	AttackIpCount int64   `protobuf:"varint,2,opt,name=attack_ip_count,json=attackIpCount,proto3" json:"attack_ip_count,omitempty"`
	AttackAdd     float32 `protobuf:"fixed32,3,opt,name=attack_add,json=attackAdd,proto3" json:"attack_add,omitempty"`
	AttackIpAdd   float32 `protobuf:"fixed32,4,opt,name=attack_ip_add,json=attackIpAdd,proto3" json:"attack_ip_add,omitempty"`
}

func (x *GetAttackInfoFromDayReply) Reset() {
	*x = GetAttackInfoFromDayReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_dashBorad_v1_message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAttackInfoFromDayReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAttackInfoFromDayReply) ProtoMessage() {}

func (x *GetAttackInfoFromDayReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_dashBorad_v1_message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAttackInfoFromDayReply.ProtoReflect.Descriptor instead.
func (*GetAttackInfoFromDayReply) Descriptor() ([]byte, []int) {
	return file_api_dashBorad_v1_message_proto_rawDescGZIP(), []int{1}
}

func (x *GetAttackInfoFromDayReply) GetAttackCount() int64 {
	if x != nil {
		return x.AttackCount
	}
	return 0
}

func (x *GetAttackInfoFromDayReply) GetAttackIpCount() int64 {
	if x != nil {
		return x.AttackIpCount
	}
	return 0
}

func (x *GetAttackInfoFromDayReply) GetAttackAdd() float32 {
	if x != nil {
		return x.AttackAdd
	}
	return 0
}

func (x *GetAttackInfoFromDayReply) GetAttackIpAdd() float32 {
	if x != nil {
		return x.AttackIpAdd
	}
	return 0
}

// #### 获取指定日志内的攻击数据 指定时间内的攻击数 , 以及异常IP数据的变化
type GetAttackInfoByTimeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetAttackInfoByTimeRequest) Reset() {
	*x = GetAttackInfoByTimeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_dashBorad_v1_message_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAttackInfoByTimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAttackInfoByTimeRequest) ProtoMessage() {}

func (x *GetAttackInfoByTimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_dashBorad_v1_message_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAttackInfoByTimeRequest.ProtoReflect.Descriptor instead.
func (*GetAttackInfoByTimeRequest) Descriptor() ([]byte, []int) {
	return file_api_dashBorad_v1_message_proto_rawDescGZIP(), []int{2}
}

type GetAttackInfoByTimeReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetAttackInfoByTimeReply) Reset() {
	*x = GetAttackInfoByTimeReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_dashBorad_v1_message_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAttackInfoByTimeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAttackInfoByTimeReply) ProtoMessage() {}

func (x *GetAttackInfoByTimeReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_dashBorad_v1_message_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAttackInfoByTimeReply.ProtoReflect.Descriptor instead.
func (*GetAttackInfoByTimeReply) Descriptor() ([]byte, []int) {
	return file_api_dashBorad_v1_message_proto_rawDescGZIP(), []int{3}
}

// #### 分类获取各个应用被攻击的信息 获取应用被攻击的信息
type GetAttackInfoFromServerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetAttackInfoFromServerRequest) Reset() {
	*x = GetAttackInfoFromServerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_dashBorad_v1_message_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAttackInfoFromServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAttackInfoFromServerRequest) ProtoMessage() {}

func (x *GetAttackInfoFromServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_dashBorad_v1_message_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAttackInfoFromServerRequest.ProtoReflect.Descriptor instead.
func (*GetAttackInfoFromServerRequest) Descriptor() ([]byte, []int) {
	return file_api_dashBorad_v1_message_proto_rawDescGZIP(), []int{4}
}

type GetAttackInfoFromServerReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetAttackInfoFromServerReply) Reset() {
	*x = GetAttackInfoFromServerReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_dashBorad_v1_message_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAttackInfoFromServerReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAttackInfoFromServerReply) ProtoMessage() {}

func (x *GetAttackInfoFromServerReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_dashBorad_v1_message_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAttackInfoFromServerReply.ProtoReflect.Descriptor instead.
func (*GetAttackInfoFromServerReply) Descriptor() ([]byte, []int) {
	return file_api_dashBorad_v1_message_proto_rawDescGZIP(), []int{5}
}

// ##### 获取异常IP来源地区
type GetAttackIpFromAddrRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetAttackIpFromAddrRequest) Reset() {
	*x = GetAttackIpFromAddrRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_dashBorad_v1_message_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAttackIpFromAddrRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAttackIpFromAddrRequest) ProtoMessage() {}

func (x *GetAttackIpFromAddrRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_dashBorad_v1_message_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAttackIpFromAddrRequest.ProtoReflect.Descriptor instead.
func (*GetAttackIpFromAddrRequest) Descriptor() ([]byte, []int) {
	return file_api_dashBorad_v1_message_proto_rawDescGZIP(), []int{6}
}

type GetAttackIpFromAddrReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetAttackIpFromAddrReply) Reset() {
	*x = GetAttackIpFromAddrReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_dashBorad_v1_message_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAttackIpFromAddrReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAttackIpFromAddrReply) ProtoMessage() {}

func (x *GetAttackIpFromAddrReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_dashBorad_v1_message_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAttackIpFromAddrReply.ProtoReflect.Descriptor instead.
func (*GetAttackIpFromAddrReply) Descriptor() ([]byte, []int) {
	return file_api_dashBorad_v1_message_proto_rawDescGZIP(), []int{7}
}

var File_api_dashBorad_v1_message_proto protoreflect.FileDescriptor

var file_api_dashBorad_v1_message_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x61, 0x70, 0x69, 0x2f, 0x64, 0x61, 0x73, 0x68, 0x42, 0x6f, 0x72, 0x61, 0x64, 0x2f,
	0x76, 0x31, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x10, 0x61, 0x70, 0x69, 0x2e, 0x64, 0x61, 0x73, 0x68, 0x42, 0x6f, 0x72, 0x61, 0x64, 0x2e,
	0x76, 0x31, 0x22, 0x1d, 0x0a, 0x1b, 0x47, 0x65, 0x74, 0x41, 0x74, 0x74, 0x61, 0x63, 0x6b, 0x49,
	0x6e, 0x66, 0x6f, 0x46, 0x72, 0x6f, 0x6d, 0x44, 0x61, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0xa9, 0x01, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x41, 0x74, 0x74, 0x61, 0x63, 0x6b, 0x49,
	0x6e, 0x66, 0x6f, 0x46, 0x72, 0x6f, 0x6d, 0x44, 0x61, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x21, 0x0a, 0x0c, 0x61, 0x74, 0x74, 0x61, 0x63, 0x6b, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x61, 0x74, 0x74, 0x61, 0x63, 0x6b, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x12, 0x26, 0x0a, 0x0f, 0x61, 0x74, 0x74, 0x61, 0x63, 0x6b, 0x5f, 0x69, 0x70, 0x5f,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x61, 0x74, 0x74,
	0x61, 0x63, 0x6b, 0x49, 0x70, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x74,
	0x74, 0x61, 0x63, 0x6b, 0x5f, 0x61, 0x64, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x09,
	0x61, 0x74, 0x74, 0x61, 0x63, 0x6b, 0x41, 0x64, 0x64, 0x12, 0x22, 0x0a, 0x0d, 0x61, 0x74, 0x74,
	0x61, 0x63, 0x6b, 0x5f, 0x69, 0x70, 0x5f, 0x61, 0x64, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02,
	0x52, 0x0b, 0x61, 0x74, 0x74, 0x61, 0x63, 0x6b, 0x49, 0x70, 0x41, 0x64, 0x64, 0x22, 0x1c, 0x0a,
	0x1a, 0x47, 0x65, 0x74, 0x41, 0x74, 0x74, 0x61, 0x63, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x42, 0x79,
	0x54, 0x69, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x1a, 0x0a, 0x18, 0x47,
	0x65, 0x74, 0x41, 0x74, 0x74, 0x61, 0x63, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x42, 0x79, 0x54, 0x69,
	0x6d, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x20, 0x0a, 0x1e, 0x47, 0x65, 0x74, 0x41, 0x74,
	0x74, 0x61, 0x63, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x46, 0x72, 0x6f, 0x6d, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x1e, 0x0a, 0x1c, 0x47, 0x65, 0x74,
	0x41, 0x74, 0x74, 0x61, 0x63, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x46, 0x72, 0x6f, 0x6d, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x1c, 0x0a, 0x1a, 0x47, 0x65, 0x74,
	0x41, 0x74, 0x74, 0x61, 0x63, 0x6b, 0x49, 0x70, 0x46, 0x72, 0x6f, 0x6d, 0x41, 0x64, 0x64, 0x72,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x1a, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x41, 0x74,
	0x74, 0x61, 0x63, 0x6b, 0x49, 0x70, 0x46, 0x72, 0x6f, 0x6d, 0x41, 0x64, 0x64, 0x72, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x42, 0x34, 0x0a, 0x10, 0x61, 0x70, 0x69, 0x2e, 0x64, 0x61, 0x73, 0x68, 0x42,
	0x6f, 0x72, 0x61, 0x64, 0x2e, 0x76, 0x31, 0x50, 0x01, 0x5a, 0x1e, 0x77, 0x61, 0x66, 0x63, 0x6f,
	0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x64, 0x61, 0x73, 0x68, 0x42, 0x6f,
	0x72, 0x61, 0x64, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_api_dashBorad_v1_message_proto_rawDescOnce sync.Once
	file_api_dashBorad_v1_message_proto_rawDescData = file_api_dashBorad_v1_message_proto_rawDesc
)

func file_api_dashBorad_v1_message_proto_rawDescGZIP() []byte {
	file_api_dashBorad_v1_message_proto_rawDescOnce.Do(func() {
		file_api_dashBorad_v1_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_dashBorad_v1_message_proto_rawDescData)
	})
	return file_api_dashBorad_v1_message_proto_rawDescData
}

var file_api_dashBorad_v1_message_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_dashBorad_v1_message_proto_goTypes = []any{
	(*GetAttackInfoFromDayRequest)(nil),    // 0: api.dashBorad.v1.GetAttackInfoFromDayRequest
	(*GetAttackInfoFromDayReply)(nil),      // 1: api.dashBorad.v1.GetAttackInfoFromDayReply
	(*GetAttackInfoByTimeRequest)(nil),     // 2: api.dashBorad.v1.GetAttackInfoByTimeRequest
	(*GetAttackInfoByTimeReply)(nil),       // 3: api.dashBorad.v1.GetAttackInfoByTimeReply
	(*GetAttackInfoFromServerRequest)(nil), // 4: api.dashBorad.v1.GetAttackInfoFromServerRequest
	(*GetAttackInfoFromServerReply)(nil),   // 5: api.dashBorad.v1.GetAttackInfoFromServerReply
	(*GetAttackIpFromAddrRequest)(nil),     // 6: api.dashBorad.v1.GetAttackIpFromAddrRequest
	(*GetAttackIpFromAddrReply)(nil),       // 7: api.dashBorad.v1.GetAttackIpFromAddrReply
}
var file_api_dashBorad_v1_message_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_dashBorad_v1_message_proto_init() }
func file_api_dashBorad_v1_message_proto_init() {
	if File_api_dashBorad_v1_message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_dashBorad_v1_message_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*GetAttackInfoFromDayRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_dashBorad_v1_message_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*GetAttackInfoFromDayReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_dashBorad_v1_message_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*GetAttackInfoByTimeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_dashBorad_v1_message_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*GetAttackInfoByTimeReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_dashBorad_v1_message_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*GetAttackInfoFromServerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_dashBorad_v1_message_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*GetAttackInfoFromServerReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_dashBorad_v1_message_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*GetAttackIpFromAddrRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_dashBorad_v1_message_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*GetAttackIpFromAddrReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_dashBorad_v1_message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_dashBorad_v1_message_proto_goTypes,
		DependencyIndexes: file_api_dashBorad_v1_message_proto_depIdxs,
		MessageInfos:      file_api_dashBorad_v1_message_proto_msgTypes,
	}.Build()
	File_api_dashBorad_v1_message_proto = out.File
	file_api_dashBorad_v1_message_proto_rawDesc = nil
	file_api_dashBorad_v1_message_proto_goTypes = nil
	file_api_dashBorad_v1_message_proto_depIdxs = nil
}
