server:
  http:
    addr: 0.0.0.0:8002
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9002
    timeout: 1s
data:
  mysql:
    host: 192.168.10.4
    port: 3310
    user: root
    password: '123456'
    db: DingHaiWAF
    max_idle: 10
    max_open: 100
  redis:
    addr: 192.168.10.4:6379
    db: 0
    password: 123456

