server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  mysql:
    host: 152.136.50.60
    port: 3306
    user: root
    password: zyf9630
    db: DingHaiWAF
    max_idle: 10
    max_open: 100
  redis:
    addr: 152.136.50.60:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
