server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  mysql:
    host: 192.168.10.4
    port: 3306
    user: root
    password: 123456
    db: DingHaiWAF
    max_idle: 10
    max_open: 100
  redis:
    addr: 192.168.10.4:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
  clickhouse:
    dsn: tcp://192.168.10.4:9000/waf?username=default&dial_timeout=10s&read_timeout=20s
  ip2:
    path: wafconsole/app/dashBorad/internal/data/model/ip2region.xdb
