// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.8.0
// - protoc             v4.25.2
// source: api/user/v1/common.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationCommonCreateNewToken = "/api.user.v1.Common/CreateNewToken"

type CommonHTTPServer interface {
	CreateNewToken(context.Context, *CreateNewTokenRequest) (*CreateNewTokenReply, error)
}

func RegisterCommonHTTPServer(s *http.Server, srv CommonHTTPServer) {
	r := s.Route("/")
	r.POST("/app/user/v1/waf/refreshToken", _Common_CreateNewToken0_HTTP_Handler(srv))
}

func _Common_CreateNewToken0_HTTP_Handler(srv CommonHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateNewTokenRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCommonCreateNewToken)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateNewToken(ctx, req.(*CreateNewTokenRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateNewTokenReply)
		return ctx.Result(200, reply)
	}
}

type CommonHTTPClient interface {
	CreateNewToken(ctx context.Context, req *CreateNewTokenRequest, opts ...http.CallOption) (rsp *CreateNewTokenReply, err error)
}

type CommonHTTPClientImpl struct {
	cc *http.Client
}

func NewCommonHTTPClient(client *http.Client) CommonHTTPClient {
	return &CommonHTTPClientImpl{client}
}

func (c *CommonHTTPClientImpl) CreateNewToken(ctx context.Context, in *CreateNewTokenRequest, opts ...http.CallOption) (*CreateNewTokenReply, error) {
	var out CreateNewTokenReply
	pattern := "/app/user/v1/waf/refreshToken"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationCommonCreateNewToken))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
