// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.8.3
// - protoc             v3.12.4
// source: v1/common.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationCommonCreateNewToken = "/api.user.v1.Common/CreateNewToken"
const OperationCommonGetCaptcha = "/api.user.v1.Common/GetCaptcha"
const OperationCommonSendCode = "/api.user.v1.Common/SendCode"
const OperationCommonSseConnect = "/api.user.v1.Common/SseConnect"
const OperationCommonVerifyCaptcha = "/api.user.v1.Common/VerifyCaptcha"

type CommonHTTPServer interface {
	CreateNewToken(context.Context, *CreateNewTokenRequest) (*CreateNewTokenReply, error)
	GetCaptcha(context.Context, *GetCaptchaRequest) (*GetCaptchaReply, error)
	SendCode(context.Context, *SendEmailRequest) (*SendEmailReply, error)
	SseConnect(context.Context, *SseConnectRequest) (*SseConnectReply, error)
	VerifyCaptcha(context.Context, *VerifyCaptchaRequest) (*VerifyCaptchaReply, error)
}

func RegisterCommonHTTPServer(s *http.Server, srv CommonHTTPServer) {
	r := s.Route("/")
	r.POST("/app/user/v1/waf/refreshToken", _Common_CreateNewToken0_HTTP_Handler(srv))
	r.GET("/app/user/v1/waf/captchaRight", _Common_GetCaptcha0_HTTP_Handler(srv))
	r.POST("/app/user/v1/waf/captchaVerify", _Common_VerifyCaptcha0_HTTP_Handler(srv))
	r.GET("/app/user/v1/waf/code", _Common_SendCode0_HTTP_Handler(srv))
	r.GET("/app/user/v1/waf/sse", _Common_SseConnect0_HTTP_Handler(srv))
}

func _Common_CreateNewToken0_HTTP_Handler(srv CommonHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateNewTokenRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCommonCreateNewToken)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateNewToken(ctx, req.(*CreateNewTokenRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateNewTokenReply)
		return ctx.Result(200, reply)
	}
}

func _Common_GetCaptcha0_HTTP_Handler(srv CommonHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetCaptchaRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCommonGetCaptcha)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetCaptcha(ctx, req.(*GetCaptchaRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetCaptchaReply)
		return ctx.Result(200, reply)
	}
}

func _Common_VerifyCaptcha0_HTTP_Handler(srv CommonHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in VerifyCaptchaRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCommonVerifyCaptcha)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.VerifyCaptcha(ctx, req.(*VerifyCaptchaRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*VerifyCaptchaReply)
		return ctx.Result(200, reply)
	}
}

func _Common_SendCode0_HTTP_Handler(srv CommonHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SendEmailRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCommonSendCode)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SendCode(ctx, req.(*SendEmailRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SendEmailReply)
		return ctx.Result(200, reply)
	}
}

func _Common_SseConnect0_HTTP_Handler(srv CommonHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SseConnectRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCommonSseConnect)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SseConnect(ctx, req.(*SseConnectRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SseConnectReply)
		return ctx.Result(200, reply)
	}
}

type CommonHTTPClient interface {
	CreateNewToken(ctx context.Context, req *CreateNewTokenRequest, opts ...http.CallOption) (rsp *CreateNewTokenReply, err error)
	GetCaptcha(ctx context.Context, req *GetCaptchaRequest, opts ...http.CallOption) (rsp *GetCaptchaReply, err error)
	SendCode(ctx context.Context, req *SendEmailRequest, opts ...http.CallOption) (rsp *SendEmailReply, err error)
	SseConnect(ctx context.Context, req *SseConnectRequest, opts ...http.CallOption) (rsp *SseConnectReply, err error)
	VerifyCaptcha(ctx context.Context, req *VerifyCaptchaRequest, opts ...http.CallOption) (rsp *VerifyCaptchaReply, err error)
}

type CommonHTTPClientImpl struct {
	cc *http.Client
}

func NewCommonHTTPClient(client *http.Client) CommonHTTPClient {
	return &CommonHTTPClientImpl{client}
}

func (c *CommonHTTPClientImpl) CreateNewToken(ctx context.Context, in *CreateNewTokenRequest, opts ...http.CallOption) (*CreateNewTokenReply, error) {
	var out CreateNewTokenReply
	pattern := "/app/user/v1/waf/refreshToken"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationCommonCreateNewToken))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *CommonHTTPClientImpl) GetCaptcha(ctx context.Context, in *GetCaptchaRequest, opts ...http.CallOption) (*GetCaptchaReply, error) {
	var out GetCaptchaReply
	pattern := "/app/user/v1/waf/captchaRight"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationCommonGetCaptcha))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *CommonHTTPClientImpl) SendCode(ctx context.Context, in *SendEmailRequest, opts ...http.CallOption) (*SendEmailReply, error) {
	var out SendEmailReply
	pattern := "/app/user/v1/waf/code"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationCommonSendCode))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *CommonHTTPClientImpl) SseConnect(ctx context.Context, in *SseConnectRequest, opts ...http.CallOption) (*SseConnectReply, error) {
	var out SseConnectReply
	pattern := "/app/user/v1/waf/sse"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationCommonSseConnect))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *CommonHTTPClientImpl) VerifyCaptcha(ctx context.Context, in *VerifyCaptchaRequest, opts ...http.CallOption) (*VerifyCaptchaReply, error) {
	var out VerifyCaptchaReply
	pattern := "/app/user/v1/waf/captchaVerify"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationCommonVerifyCaptcha))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
