// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/go-kratos/kratos/v2/registry"
	"wafconsole/app/mqconsume/internal/biz/notice"
	"wafconsole/app/mqconsume/internal/conf"
	"wafconsole/app/mqconsume/internal/data"
	"wafconsole/app/mqconsume/internal/server"
	notice2 "wafconsole/app/mqconsume/internal/service/notice"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
//
//go:generate wire
func wireApp(confServer *conf.Server, confData *conf.Data, confRegistry *conf.Registry, logger log.Logger, registrar registry.Registrar) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	userNoticeRepo := data.NewNoticeUserRepo(dataData, logger)
	userNoticeUsecase := notice.NewUserNoticeUsecase(userNoticeRepo, logger)
	msgNoticeService := notice2.NewNoticeMsgService(logger, userNoticeUsecase)
	rabbitmqServer := server.NewRabbitMQServer(confData, logger, msgNoticeService)
	app := newApp(logger, rabbitmqServer, registrar)
	return app, func() {
		cleanup()
	}, nil
}
