// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/go-kratos/kratos/v2/registry"
	"wafconsole/app/user/internal/biz"
	"wafconsole/app/user/internal/conf"
	"wafconsole/app/user/internal/data"
	"wafconsole/app/user/internal/server"
	"wafconsole/app/user/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
//
//go:generate wire
func wireApp(confServer *conf.Server, bootstrap *conf.Bootstrap, logger log.Logger, registrar registry.Registrar) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confServer, bootstrap)
	if err != nil {
		return nil, nil, err
	}
	wafUserRepo := data.NewWafUserRepo(dataData)
	wafUserUsecase := biz.NewWafUserUsecase(wafUserRepo)
	wafUserService := service.NewWafUserService(wafUserUsecase)
	wafUserCommonRepo := data.NewWafUserCommonRepo(dataData)
	wafUserCommonUsecase := biz.NewWafUserCommonUsecase(wafUserCommonRepo)
	commonService := service.NewCommonService(wafUserCommonUsecase)
	grpcServer := server.NewGRPCServer(confServer, wafUserService, commonService, logger)
	httpServer := server.NewHTTPServer(confServer, wafUserService, commonService, logger)
	app := newApp(logger, grpcServer, httpServer, registrar)
	return app, func() {
		cleanup()
	}, nil
}
